
package hays.com.career.dextra.emailService;

import intradoc.shared.SharedObjects;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.1 in JDK 6
 * Generated source version: 2.1
 * 
 */
@WebServiceClient(name = "JobService", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://hrlvmat1263.emea.hays.loc:3015/Services/JobService.svc?wsdl")
public class JobService
    extends Service
{

    private final static URL JOBSERVICE_WSDL_LOCATION;

    static {
        URL url = null;
        String endPoint=SharedObjects.getEnvironmentValue("WSDL_ENDPOINT_GC_DEXTRA");
        try {
            url = new URL(endPoint);
        } catch (MalformedURLException e) {
            e.printStackTrace();
        }
        JOBSERVICE_WSDL_LOCATION = url;
    }

    public JobService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public JobService() {
        super(JOBSERVICE_WSDL_LOCATION, new QName("http://tempuri.org/", "JobService"));
    }

    /**
     * 
     * @return
     *     returns IJobService
     */
    @WebEndpoint(name = "WSHttpBinding_IJobService")
    public IJobService getWSHttpBindingIJobService() {
        return (IJobService)super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IJobService"), IJobService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IJobService
     */
    @WebEndpoint(name = "WSHttpBinding_IJobService")
    public IJobService getWSHttpBindingIJobService(WebServiceFeature... features) {
        return (IJobService)super.getPort(new QName("http://tempuri.org/", "WSHttpBinding_IJobService"), IJobService.class, features);
    }

    /**
     * 
     * @return
     *     returns IJobService
     */
    @WebEndpoint(name = "BasicHttpBinding_IJobService")
    public IJobService getBasicHttpBindingIJobService() {
        return (IJobService)super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IJobService"), IJobService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IJobService
     */
    @WebEndpoint(name = "BasicHttpBinding_IJobService")
    public IJobService getBasicHttpBindingIJobService(WebServiceFeature... features) {
        return (IJobService)super.getPort(new QName("http://tempuri.org/", "BasicHttpBinding_IJobService"), IJobService.class, features);
    }

    /**
     * 
     * @return
     *     returns IJobService
     */
    @WebEndpoint(name = "CustomBinding_IJobService")
    public IJobService getCustomBindingIJobService() {
        return (IJobService)super.getPort(new QName("http://tempuri.org/", "CustomBinding_IJobService"), IJobService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns IJobService
     */
    @WebEndpoint(name = "CustomBinding_IJobService")
    public IJobService getCustomBindingIJobService(WebServiceFeature... features) {
        return (IJobService)super.getPort(new QName("http://tempuri.org/", "CustomBinding_IJobService"), IJobService.class, features);
    }

}
